import Nav from '@/components/nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/components/provider'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Nav />
          {children}
          {/* <Footer /> */}
        </Provider>
      </body>
    </html>
  )
}
